from __future__ import annotations

SOURCES = [
    {
        "id": "uk_unclaimed_estates",
        "name": "UK Bona Vacantia unclaimed estates",
        "kind": "csv",
        "access": "public",
        "action_gate": "owner_or_heir_only",
        "url": "https://www.gov.uk/government/statistical-data-sets/unclaimed-estates-list",
    },
    {
        "id": "ca_unclaimed_property",
        "name": "California State Controller public unclaimed-property records",
        "kind": "zip_csv",
        "access": "public",
        "action_gate": "agreement_and_law_review",
        "url": "https://www.sco.ca.gov/upd_download_property_records.html",
    },
    {
        "id": "ny_unclaimed_property",
        "name": "New York Office of Unclaimed Funds owner-name file",
        "kind": "secure_download_file",
        "access": "request_required",
        "action_gate": "agreement_required",
        "url": "https://www.osc.ny.gov/unclaimed-funds/resources/location-service-providers",
    },
    {
        "id": "uspto_official_gazette",
        "name": "USPTO Official Gazette",
        "kind": "html",
        "access": "public",
        "action_gate": "public_intelligence_only",
        "url": "https://www.uspto.gov/learning-and-resources/official-gazette",
    },
    {
        "id": "uspto_open_data",
        "name": "USPTO Open Data Portal",
        "kind": "api_bulk",
        "access": "account_and_api_key",
        "action_gate": "public_intelligence_only",
        "url": "https://data.uspto.gov/",
    },
    {
        "id": "flc_license_notices",
        "name": "Federal Laboratory Consortium licensing notices",
        "kind": "html",
        "access": "public",
        "action_gate": "public_intelligence_only",
        "url": "https://federallabs.org/flc-business/notice-of-intent-to-license",
    },
    {
        "id": "companies_house_stream",
        "name": "Companies House real-time company stream",
        "kind": "stream",
        "access": "stream_key",
        "action_gate": "public_intelligence_only",
        "url": "https://developer-specs.company-information.service.gov.uk/streaming-api/reference",
    },
    {
        "id": "companies_house",
        "name": "Companies House",
        "kind": "api",
        "access": "api_key",
        "action_gate": "public_intelligence_only",
        "url": "https://developer.company-information.service.gov.uk/",
    },
    {
        "id": "usaspending",
        "name": "USAspending V2",
        "kind": "api",
        "access": "public",
        "action_gate": "public_intelligence_only",
        "url": "https://api.usaspending.gov/",
    },
    {
        "id": "mlc_data",
        "name": "The MLC data programs",
        "kind": "api_bulk",
        "access": "enrollment_required",
        "action_gate": "public_intelligence_only",
        "url": "https://www.themlc.com/dataprograms",
    },
    {
        "id": "us_bankruptcy_unclaimed",
        "name": "U.S. Bankruptcy Unclaimed Funds Locator",
        "kind": "interactive_search",
        "access": "public_captcha",
        "action_gate": "court_entitlement_review_required",
        "url": "https://ucf.uscourts.gov/",
    },
    {
        "id": "soundexchange_unclaimed",
        "name": "SoundExchange unclaimed creator/rightsholder status lists",
        "kind": "search",
        "access": "public",
        "action_gate": "public_intelligence_only",
        "url": "https://www.soundexchange.com/what-we-do/for-artists-labels-and-producers/",
    },
    {
        "id": "treasury_unpaid_checks_foia",
        "name": "U.S. Treasury canceled/unpaid federal check records",
        "kind": "foia_or_agency_file",
        "access": "lawfully_obtained_file",
        "action_gate": "payee_identification_and_legal_review",
        "url": "https://fiscal.treasury.gov/about-us/unclaimed-assets",
    },
    {
        "id": "sam_contract_opportunities",
        "name": "SAM.gov public Contract Opportunities data",
        "kind": "public_csv_or_api",
        "access": "public",
        "action_gate": "public_intelligence_only",
        "url": "https://sam.gov/data-services/Contract%20Opportunities/datagov?privacy=Public",
    },
    {
        "id": "uk_bona_vacantia_company_assets",
        "name": "UK dissolved-company bona vacantia asset referral/purchase process",
        "kind": "official_referral_process",
        "access": "public_guidance",
        "action_gate": "title_valuation_and_purchase_review",
        "url": "https://www.gov.uk/claiming-money-or-property-from-dissolved-company/buy-dissolved-company-assets",
    },
    {
        "id": "official_surplus_funds",
        "name": "Official county/court surplus-funds file",
        "kind": "official_file_import",
        "access": "public_or_lawfully_obtained_file",
        "action_gate": "jurisdiction_specific_entitlement_and_fee_review",
        "url": "official-source-url-required-at-ingest",
    },
]
